# Generated by Django 2.1.15 on 2020-09-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200922_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
